// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpu2P-um5CYSmZLwdG3plppDATTC1bEA',
    appId: '1:805408553212:web:a98741274166ef1cd2bf79',
    messagingSenderId: '805408553212',
    projectId: 'chat-app-78b8c',
    authDomain: 'chat-app-78b8c.firebaseapp.com',
    storageBucket: 'chat-app-78b8c.firebasestorage.app',
    measurementId: 'G-XLBCTVHB7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgCuzeA-RijtXgiW9v5Ltgx9w63NSZaU',
    appId: '1:805408553212:android:eb9dc306ffbf341cd2bf79',
    messagingSenderId: '805408553212',
    projectId: 'chat-app-78b8c',
    storageBucket: 'chat-app-78b8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxcIoOdxsk86buRbg3kPDndwl21AnZ40',
    appId: '1:805408553212:ios:5795f1f0ee3e56abd2bf79',
    messagingSenderId: '805408553212',
    projectId: 'chat-app-78b8c',
    storageBucket: 'chat-app-78b8c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxcIoOdxsk86buRbg3kPDndwl21AnZ40',
    appId: '1:805408553212:ios:5795f1f0ee3e56abd2bf79',
    messagingSenderId: '805408553212',
    projectId: 'chat-app-78b8c',
    storageBucket: 'chat-app-78b8c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYpu2P-um5CYSmZLwdG3plppDATTC1bEA',
    appId: '1:805408553212:web:7523e52f8286eba5d2bf79',
    messagingSenderId: '805408553212',
    projectId: 'chat-app-78b8c',
    authDomain: 'chat-app-78b8c.firebaseapp.com',
    storageBucket: 'chat-app-78b8c.firebasestorage.app',
    measurementId: 'G-TWMFJ80Q2R',
  );
}
